### ISSUE TITLE
TRACE nova ValueError: The network range is not big enough to fit 1. Network size is 512

### ISSUE THREAD

**Issue by cmoulliard** [uksysadmin/OpenStackInstaller#13]
Hi,

I get this error message during installation process :
- Command used : ./OSinstall.sh -F 192.168.1.192/27 -f 10.0.2.0/24 -s 512 -P eth0 -p eth1 -t demo -v qemu
- Message received : 

2012-08-22 10:22:47 CRITICAL nova [req-1763abcd-267c-4a29-bd04-eb9b4d6a8320 None None] The network range is not big enough to fit 1. Network size is 512
2012-08-22 10:22:47 TRACE nova Traceback (most recent call last):
2012-08-22 10:22:47 TRACE nova   File "/usr/bin/nova-manage", line 1746, in <module>
2012-08-22 10:22:47 TRACE nova     main()
2012-08-22 10:22:47 TRACE nova   File "/usr/bin/nova-manage", line 1733, in main
2012-08-22 10:22:47 TRACE nova     fn(_fn_args, *_fn_kwargs)
2012-08-22 10:22:47 TRACE nova   File "/usr/bin/nova-manage", line 812, in create
2012-08-22 10:22:47 TRACE nova     fixed_cidr=fixed_cidr)
2012-08-22 10:22:47 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/network/manager.py", line 1836, in create_networks
2012-08-22 10:22:47 TRACE nova     kwargs)
2012-08-22 10:22:47 TRACE nova ValueError: The network range is not big enough to fit 1. Network size is 512
2012-08-22 10:22:47 TRACE nova 
2012-08-22 10:22:48 DEBUG nova.utils [req-1000fa7f-2571-42a3-8827-a9c9fc47b5d6 None None] backend <module 'nova.db.sqlalchemy.api' from '/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.pyc'> from (pid=14181) __get_backend /usr/lib/python2.7/dist-packages/nova/utils.py:658

Regards,

Charles

**Comment by cmoulliard** [comment]
Find the response here : https://answers.launchpad.net/nova/+question/172683

I have adapted the command to use 256 instead of 512.
